language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=">=1.10,<1.11"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.8,<1.9"

install: pip install -r requirements_test.txt Django$DJANGO_VERSION python-binary-memcached
script: ./.travis-runs-tests.sh
